version: '3.8'

services:
  # Your FastAPI Application
  letter-app:
    build: .
    container_name: fastapi_letter_program
    restart: always
    # We don't expose ports here because only NGINX needs to talk to it
    networks:
      - letter-network

  # Your NGINX Reverse Proxy & Load Balancer
  nginx-proxy:
    image: nginx:latest
    container_name: nginx_gatekeeper
    restart: always
    ports:
      - "8080:80" # Maps your Windows Port 80 to NGINX Port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/usr/share/nginx/html/static:ro
    depends_on:
      - letter-app
    networks:
      - letter-network

networks:
  letter-network:
    driver: bridge