events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Load Balancer Configuration
    # 'letter-app' matches the service name in our docker-compose file
    upstream fastapi_backend {
        server letter-app:8000;
    }

    server {
        listen 80;
        server_name localhost; # Replace with your domain or Public IP later

        # Forward all requests to FastAPI/Uvicorn
        location / {
            proxy_pass http://fastapi_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # NGINX serves the sounds and images directly for better performance
        location /static/ {
            alias /usr/share/nginx/html/static/;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }
    }
}